
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbxMain;
	
	private global::Gtk.VBox vbxPlot;
	
	private global::Gtk.HBox hbxMixer;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.VScale vscaleSetpoint;
	
	private global::Gtk.Label lblSetpoint;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.VScale vscaleDeadTime;
	
	private global::Gtk.Label lblDeadTime;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.VScale vscaleSpeed;
	
	private global::Gtk.Label lblDeadTime1;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.VScale vscaleDeadTime2;
	
	private global::Gtk.Label lblDeadTime2;
	
	private global::Gtk.VBox vbox5;
	
	private global::Gtk.VScale vscaleDeadTime3;
	
	private global::Gtk.Label lblDeadTime3;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Limbus Laboratory");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbxMain = new global::Gtk.VBox ();
		this.vbxMain.Name = "vbxMain";
		this.vbxMain.Spacing = 6;
		// Container child vbxMain.Gtk.Box+BoxChild
		this.vbxPlot = new global::Gtk.VBox ();
		this.vbxPlot.Name = "vbxPlot";
		this.vbxPlot.Spacing = 6;
		this.vbxMain.Add (this.vbxPlot);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbxMain [this.vbxPlot]));
		w1.Position = 0;
		// Container child vbxMain.Gtk.Box+BoxChild
		this.hbxMixer = new global::Gtk.HBox ();
		this.hbxMixer.Name = "hbxMixer";
		this.hbxMixer.Spacing = 6;
		// Container child hbxMixer.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.vscaleSetpoint = new global::Gtk.VScale (null);
		this.vscaleSetpoint.CanFocus = true;
		this.vscaleSetpoint.Name = "vscaleSetpoint";
		this.vscaleSetpoint.Inverted = true;
		this.vscaleSetpoint.Adjustment.Lower = -100;
		this.vscaleSetpoint.Adjustment.Upper = 100;
		this.vscaleSetpoint.Adjustment.PageIncrement = 10;
		this.vscaleSetpoint.Adjustment.StepIncrement = 1;
		this.vscaleSetpoint.Adjustment.Value = 15;
		this.vscaleSetpoint.DrawValue = true;
		this.vscaleSetpoint.Digits = 0;
		this.vscaleSetpoint.ValuePos = ((global::Gtk.PositionType)(2));
		this.vbox4.Add (this.vscaleSetpoint);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vscaleSetpoint]));
		w2.Position = 0;
		// Container child vbox4.Gtk.Box+BoxChild
		this.lblSetpoint = new global::Gtk.Label ();
		this.lblSetpoint.Name = "lblSetpoint";
		this.lblSetpoint.LabelProp = global::Mono.Unix.Catalog.GetString ("Setpoint");
		this.vbox4.Add (this.lblSetpoint);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblSetpoint]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		this.hbxMixer.Add (this.vbox4);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbxMixer [this.vbox4]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbxMixer.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vscaleDeadTime = new global::Gtk.VScale (null);
		this.vscaleDeadTime.CanFocus = true;
		this.vscaleDeadTime.Name = "vscaleDeadTime";
		this.vscaleDeadTime.Inverted = true;
		this.vscaleDeadTime.Adjustment.Upper = 100;
		this.vscaleDeadTime.Adjustment.PageIncrement = 10;
		this.vscaleDeadTime.Adjustment.StepIncrement = 1;
		this.vscaleDeadTime.DrawValue = true;
		this.vscaleDeadTime.Digits = 0;
		this.vscaleDeadTime.ValuePos = ((global::Gtk.PositionType)(2));
		this.vbox3.Add (this.vscaleDeadTime);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vscaleDeadTime]));
		w5.Position = 0;
		// Container child vbox3.Gtk.Box+BoxChild
		this.lblDeadTime = new global::Gtk.Label ();
		this.lblDeadTime.Name = "lblDeadTime";
		this.lblDeadTime.LabelProp = global::Mono.Unix.Catalog.GetString ("DeadTime");
		this.vbox3.Add (this.lblDeadTime);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lblDeadTime]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		this.hbxMixer.Add (this.vbox3);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbxMixer [this.vbox3]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbxMixer.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vscaleSpeed = new global::Gtk.VScale (null);
		this.vscaleSpeed.CanFocus = true;
		this.vscaleSpeed.Name = "vscaleSpeed";
		this.vscaleSpeed.Adjustment.Upper = 1000;
		this.vscaleSpeed.Adjustment.PageIncrement = 10;
		this.vscaleSpeed.Adjustment.StepIncrement = 1;
		this.vscaleSpeed.Adjustment.Value = 1000;
		this.vscaleSpeed.DrawValue = true;
		this.vscaleSpeed.Digits = 0;
		this.vscaleSpeed.ValuePos = ((global::Gtk.PositionType)(2));
		this.vbox1.Add (this.vscaleSpeed);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vscaleSpeed]));
		w8.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.lblDeadTime1 = new global::Gtk.Label ();
		this.lblDeadTime1.Name = "lblDeadTime1";
		this.lblDeadTime1.LabelProp = global::Mono.Unix.Catalog.GetString ("Speed");
		this.vbox1.Add (this.lblDeadTime1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.lblDeadTime1]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		this.hbxMixer.Add (this.vbox1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbxMixer [this.vbox1]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbxMixer.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vscaleDeadTime2 = new global::Gtk.VScale (null);
		this.vscaleDeadTime2.CanFocus = true;
		this.vscaleDeadTime2.Name = "vscaleDeadTime2";
		this.vscaleDeadTime2.Inverted = true;
		this.vscaleDeadTime2.Adjustment.Upper = 100;
		this.vscaleDeadTime2.Adjustment.PageIncrement = 10;
		this.vscaleDeadTime2.Adjustment.StepIncrement = 1;
		this.vscaleDeadTime2.DrawValue = true;
		this.vscaleDeadTime2.Digits = 0;
		this.vscaleDeadTime2.ValuePos = ((global::Gtk.PositionType)(2));
		this.vbox2.Add (this.vscaleDeadTime2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vscaleDeadTime2]));
		w11.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.lblDeadTime2 = new global::Gtk.Label ();
		this.lblDeadTime2.Name = "lblDeadTime2";
		this.lblDeadTime2.LabelProp = global::Mono.Unix.Catalog.GetString ("?");
		this.vbox2.Add (this.lblDeadTime2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblDeadTime2]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		this.hbxMixer.Add (this.vbox2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbxMixer [this.vbox2]));
		w13.Position = 3;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbxMixer.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.vscaleDeadTime3 = new global::Gtk.VScale (null);
		this.vscaleDeadTime3.CanFocus = true;
		this.vscaleDeadTime3.Name = "vscaleDeadTime3";
		this.vscaleDeadTime3.Inverted = true;
		this.vscaleDeadTime3.Adjustment.Upper = 100;
		this.vscaleDeadTime3.Adjustment.PageIncrement = 10;
		this.vscaleDeadTime3.Adjustment.StepIncrement = 1;
		this.vscaleDeadTime3.DrawValue = true;
		this.vscaleDeadTime3.Digits = 0;
		this.vscaleDeadTime3.ValuePos = ((global::Gtk.PositionType)(2));
		this.vbox5.Add (this.vscaleDeadTime3);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.vscaleDeadTime3]));
		w14.Position = 0;
		// Container child vbox5.Gtk.Box+BoxChild
		this.lblDeadTime3 = new global::Gtk.Label ();
		this.lblDeadTime3.Name = "lblDeadTime3";
		this.lblDeadTime3.LabelProp = global::Mono.Unix.Catalog.GetString ("?");
		this.vbox5.Add (this.lblDeadTime3);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.lblDeadTime3]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		this.hbxMixer.Add (this.vbox5);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbxMixer [this.vbox5]));
		w16.Position = 4;
		w16.Expand = false;
		w16.Fill = false;
		this.vbxMain.Add (this.hbxMixer);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbxMain [this.hbxMixer]));
		w17.Position = 1;
		this.Add (this.vbxMain);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.vscaleSetpoint.ValueChanged += new global::System.EventHandler (this.vScaleSetpoint_Changed);
		this.vscaleDeadTime.ValueChanged += new global::System.EventHandler (this.vscaleDeadTime_Changed);
		this.vscaleSpeed.ValueChanged += new global::System.EventHandler (this.vScaleSpeed_Changed);
	}
}
